// Agent integration helper for the Design-System Registry.
//
// When the agent receives a UI generation request (e.g. "build me a
// dashboard") and the user hasn't pinned a design system, the agent
// MUST call `ask_user_question` with the design-system pack options
// generated by this helper. This replaces per-turn ad-hoc palette /
// font / spacing decisions with a single, deliberate user choice.
//
// Usage (from inside the agent runner):
//
//   import { buildDesignSystemQuestion } from '@/lib/design-systems/agent-helper';
//
//   const question = await buildDesignSystemQuestion();
//   // → pass to the existing `ask_user_question` tool.

import { listPacks } from './loader';
import type { PackSummary } from './types';

// ── Types ────────────────────────────────────────────────────────────

export interface AskUserQuestionOption {
  label: string;
  description?: string;
}

export interface AskUserQuestionSpec {
  question: string;
  header?: string;
  multiSelect?: boolean;
  options: AskUserQuestionOption[];
}

// ── Builder ──────────────────────────────────────────────────────────

/**
 * Build the AskUserQuestion spec for picking a design-system pack.
 *
 * Each pack becomes one option:
 *   label:       pack name (human-readable, e.g. "shadcn/ui (Recommended)")
 *   description: pack.description from the registry (≤160 chars)
 *
 * The first option is the registry's `defaultPack`, marked with the
 * "(Recommended)" suffix per the ask-user-question guideline.
 */
export async function buildDesignSystemQuestion(): Promise<AskUserQuestionSpec> {
  const packs = await listPacks();

  const options: AskUserQuestionOption[] = packs.map((pack) => {
    const isDefault = pack.isDefault;
    const label = isDefault
      ? `${humanifyPackName(pack.name)} (Recommended)`
      : humanifyPackName(pack.name);
    const paletteHint = `${pack.palette.primary} / ${pack.palette.accent}`;
    const tags = pack.bestFor.join(', ');
    return {
      label,
      description: `${pack.description} [palette: ${paletteHint} · best for: ${tags}]`,
    };
  });

  return {
    question:
      'Which design system should I use for this UI? Pick one — the choice pins palette, fonts, spacing, and component imports for all subsequent generations in this session.',
    header: 'Design system',
    multiSelect: false,
    options,
  };
}

/**
 * Convert a pack's kebab-case `name` to a human-readable label.
 * e.g. "shadcn-default" → "shadcn/ui", "vercel-geist" → "Vercel Geist".
 */
function humanifyPackName(name: string): string {
  const known: Record<string, string> = {
    'shadcn-default': 'shadcn/ui',
    'vercel-geist': 'Vercel Geist',
    'mantine-default': 'Mantine',
  };
  return known[name] ?? name.split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

// ── System prompt fragment ────────────────────────────────────────────

/**
 * A string the agent's system prompt can append verbatim. Tells the
 * agent the registry exists and to use `ask_user_question` to pick a
 * pack before generating UI.
 */
export const DESIGN_SYSTEM_SYSTEM_PROMPT_FRAGMENT = `
## Design-System Registry

When the user asks you to generate UI (dashboard, page, form, etc.) and they
have not pinned a design system in their request, you MUST call
\`ask_user_question\` with the design-system pack options BEFORE generating
any UI. The available packs live in the registry at
\`src/lib/design-systems/registry.json\` and are served by the
\`GET /api/design-systems\` endpoint. Use the helper
\`buildDesignSystemQuestion()\` from \`@/lib/design-systems/agent-helper\`
to build the question spec — it returns the latest packs with the
registry's default marked "(Recommended)".

After the user picks a pack:
1. Load \`tokens.css\` from \`src/lib/design-systems/packs/<pack-name>/\`
   and inject it into the app's \`globals.css\` (or directly into a
   \`<style>\` tag scoped to the page being generated).
2. Use the pack's \`importMap\` to know where to import Button, Input,
   Card, Dialog, Table, Toast, Tabs, Avatar.
3. Iron rule: never hardcode hex colors, spacing, or font values —
   always reference \`var(--*)\` from the pack's tokens.
4. If a pack's dependency is missing (e.g. user picked vercel-geist
   but \`geist\` is not installed), fall back to the default pack
   (shadcn-default) and warn the user.
`.trim();
